# NumPy image analysis

In [1]:
import numpy as np

In [2]:
ones_arr = np.ones((3, 3))

In [3]:
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
ones_arr = np.ones((5, 5), dtype = int)

In [5]:
ones_arr 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
zeros_arr = np.zeros((3, 3))

In [7]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
zeros_arr = np.zeros((3, 3), dtype = int)

In [9]:
zeros_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
ones_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
ones_arr * 255

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255]])

In [12]:
zeros_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
ones_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
import matplotlib.pyplot as plt

In [15]:
%matplotlib inline 

In [16]:
from PIL import Image # Python Imaging Library

In [17]:
horse_img = Image.open(r'D:\Full Stack Data Science & Gen AI With Agentic AI Notes\Notes\March\27 March\Image analysis\Horse.jpg')

In [ ]:
horse_img

In [18]:
type(horse_img)

PIL.JpegImagePlugin.JpegImageFile

In [19]:
horse_arr = np.asarray(horse_img)
horse_arr

array([[[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [29, 40, 36],
        [26, 37, 33],
        [20, 31, 27]],

       [[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [31, 42, 38],
        [28, 39, 35],
        [23, 34, 30]],

       [[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [33, 44, 40],
        [30, 41, 37],
        [26, 37, 33]],

       ...,

       [[38, 40, 29],
        [44, 47, 38],
        [38, 43, 36],
        ...,
        [18, 32, 32],
        [ 9, 25, 24],
        [ 9, 25, 24]],

       [[39, 34, 28],
        [41, 38, 33],
        [37, 33, 30],
        ...,
        [16, 28, 28],
        [16, 30, 30],
        [23, 37, 37]],

       [[37, 44, 36],
        [36, 43, 35],
        [35, 42, 35],
        ...,
        [17, 29, 29],
        [16, 28, 28],
        [19, 33, 33]]], shape=(1999, 3000, 3), dtype=uint8)

In [20]:
type(horse_arr)

numpy.ndarray

In [21]:
horse_arr.shape

(1999, 3000, 3)

In [ ]:
plt.imshow(horse_arr)

In [22]:
horse_red = horse_arr.copy()

In [23]:
horse_red

array([[[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [29, 40, 36],
        [26, 37, 33],
        [20, 31, 27]],

       [[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [31, 42, 38],
        [28, 39, 35],
        [23, 34, 30]],

       [[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [33, 44, 40],
        [30, 41, 37],
        [26, 37, 33]],

       ...,

       [[38, 40, 29],
        [44, 47, 38],
        [38, 43, 36],
        ...,
        [18, 32, 32],
        [ 9, 25, 24],
        [ 9, 25, 24]],

       [[39, 34, 28],
        [41, 38, 33],
        [37, 33, 30],
        ...,
        [16, 28, 28],
        [16, 30, 30],
        [23, 37, 37]],

       [[37, 44, 36],
        [36, 43, 35],
        [35, 42, 35],
        ...,
        [17, 29, 29],
        [16, 28, 28],
        [19, 33, 33]]], shape=(1999, 3000, 3), dtype=uint8)

In [24]:
horse_arr == horse_red

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       ...,

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,

In [ ]:
plt.imshow(horse_red)

In [25]:
horse_red.shape

(1999, 3000, 3)

In [ ]:
# RGB = Red, Green, Blue

plt.imshow(horse_red[:, :, 0])

In [26]:
horse_red[:, :, 0]

array([[15, 15, 15, ..., 29, 26, 20],
       [15, 15, 15, ..., 31, 28, 23],
       [15, 15, 15, ..., 33, 30, 26],
       ...,
       [38, 44, 38, ..., 18,  9,  9],
       [39, 41, 37, ..., 16, 16, 23],
       [37, 36, 35, ..., 17, 16, 19]], shape=(1999, 3000), dtype=uint8)

In [ ]:
plt.imshow(horse_red[:, :, 0], cmap = 'Greys')

In [ ]:
plt.imshow(horse_red[:, :, 1], cmap = 'grey')

In [ ]:
plt.imshow(horse_red[:, :, 2], cmap = 'grey')

In [27]:
horse_red[:, :, 0]

array([[15, 15, 15, ..., 29, 26, 20],
       [15, 15, 15, ..., 31, 28, 23],
       [15, 15, 15, ..., 33, 30, 26],
       ...,
       [38, 44, 38, ..., 18,  9,  9],
       [39, 41, 37, ..., 16, 16, 23],
       [37, 36, 35, ..., 17, 16, 19]], shape=(1999, 3000), dtype=uint8)

In [28]:
horse_red[:, :, 1]

array([[17, 17, 17, ..., 40, 37, 31],
       [17, 17, 17, ..., 42, 39, 34],
       [17, 17, 17, ..., 44, 41, 37],
       ...,
       [40, 47, 43, ..., 32, 25, 25],
       [34, 38, 33, ..., 28, 30, 37],
       [44, 43, 42, ..., 29, 28, 33]], shape=(1999, 3000), dtype=uint8)

In [29]:
horse_red[:, :, 2]

array([[29, 29, 29, ..., 36, 33, 27],
       [29, 29, 29, ..., 38, 35, 30],
       [29, 29, 29, ..., 40, 37, 33],
       ...,
       [29, 38, 36, ..., 32, 24, 24],
       [28, 33, 30, ..., 28, 30, 37],
       [36, 35, 35, ..., 29, 28, 33]], shape=(1999, 3000), dtype=uint8)

In [30]:
horse_red[:, :, 1] = 0

In [31]:
horse_red[:, :, 1]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1999, 3000), dtype=uint8)

In [ ]:
plt.imshow(horse_red)

In [32]:
horse_red[:, :, 2]

array([[29, 29, 29, ..., 36, 33, 27],
       [29, 29, 29, ..., 38, 35, 30],
       [29, 29, 29, ..., 40, 37, 33],
       ...,
       [29, 38, 36, ..., 32, 24, 24],
       [28, 33, 30, ..., 28, 30, 37],
       [36, 35, 35, ..., 29, 28, 33]], shape=(1999, 3000), dtype=uint8)

In [33]:
horse_red[:, :, 2] = 0

In [34]:
horse_red[:, :, 2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1999, 3000), dtype=uint8)

In [ ]:
plt.imshow(horse_red)

In [35]:
horse_arr

array([[[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [29, 40, 36],
        [26, 37, 33],
        [20, 31, 27]],

       [[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [31, 42, 38],
        [28, 39, 35],
        [23, 34, 30]],

       [[15, 17, 29],
        [15, 17, 29],
        [15, 17, 29],
        ...,
        [33, 44, 40],
        [30, 41, 37],
        [26, 37, 33]],

       ...,

       [[38, 40, 29],
        [44, 47, 38],
        [38, 43, 36],
        ...,
        [18, 32, 32],
        [ 9, 25, 24],
        [ 9, 25, 24]],

       [[39, 34, 28],
        [41, 38, 33],
        [37, 33, 30],
        ...,
        [16, 28, 28],
        [16, 30, 30],
        [23, 37, 37]],

       [[37, 44, 36],
        [36, 43, 35],
        [35, 42, 35],
        ...,
        [17, 29, 29],
        [16, 28, 28],
        [19, 33, 33]]], shape=(1999, 3000, 3), dtype=uint8)

In [36]:
horse_red

array([[[15,  0,  0],
        [15,  0,  0],
        [15,  0,  0],
        ...,
        [29,  0,  0],
        [26,  0,  0],
        [20,  0,  0]],

       [[15,  0,  0],
        [15,  0,  0],
        [15,  0,  0],
        ...,
        [31,  0,  0],
        [28,  0,  0],
        [23,  0,  0]],

       [[15,  0,  0],
        [15,  0,  0],
        [15,  0,  0],
        ...,
        [33,  0,  0],
        [30,  0,  0],
        [26,  0,  0]],

       ...,

       [[38,  0,  0],
        [44,  0,  0],
        [38,  0,  0],
        ...,
        [18,  0,  0],
        [ 9,  0,  0],
        [ 9,  0,  0]],

       [[39,  0,  0],
        [41,  0,  0],
        [37,  0,  0],
        ...,
        [16,  0,  0],
        [16,  0,  0],
        [23,  0,  0]],

       [[37,  0,  0],
        [36,  0,  0],
        [35,  0,  0],
        ...,
        [17,  0,  0],
        [16,  0,  0],
        [19,  0,  0]]], shape=(1999, 3000, 3), dtype=uint8)

In [ ]:
horse_img

In [37]:
arr1 = np.asarray(horse_img)

In [38]:
type(arr1)

numpy.ndarray

In [39]:
arr1.shape

(1999, 3000, 3)

In [ ]:
plt.imshow(arr1)

In [40]:
horse_img1 = arr1.copy()

In [41]:
horse_img1[:, :, 0]

array([[15, 15, 15, ..., 29, 26, 20],
       [15, 15, 15, ..., 31, 28, 23],
       [15, 15, 15, ..., 33, 30, 26],
       ...,
       [38, 44, 38, ..., 18,  9,  9],
       [39, 41, 37, ..., 16, 16, 23],
       [37, 36, 35, ..., 17, 16, 19]], shape=(1999, 3000), dtype=uint8)

In [42]:
horse_img1[:, :, 0] = 0

In [ ]:
plt.imshow(horse_img1)

In [43]:
horse_img1 = arr1.copy()

In [44]:
horse_img1[:, :, 1]

array([[17, 17, 17, ..., 40, 37, 31],
       [17, 17, 17, ..., 42, 39, 34],
       [17, 17, 17, ..., 44, 41, 37],
       ...,
       [40, 47, 43, ..., 32, 25, 25],
       [34, 38, 33, ..., 28, 30, 37],
       [44, 43, 42, ..., 29, 28, 33]], shape=(1999, 3000), dtype=uint8)

In [45]:
horse_img1[:, :, 1] = 0

In [ ]:
plt.imshow(horse_img1)

In [46]:
horse_img1 = arr1.copy()

In [47]:
horse_img1[:, :, 2]

array([[29, 29, 29, ..., 36, 33, 27],
       [29, 29, 29, ..., 38, 35, 30],
       [29, 29, 29, ..., 40, 37, 33],
       ...,
       [29, 38, 36, ..., 32, 24, 24],
       [28, 33, 30, ..., 28, 30, 37],
       [36, 35, 35, ..., 29, 28, 33]], shape=(1999, 3000), dtype=uint8)

In [48]:
horse_img1[:, :, 2] = 0

In [ ]:
plt.imshow(horse_img1)