# NumPy advance functions

## Array creation functions

In [1]:
import numpy as np

In [2]:
# Create an array from a list

a = np.array([1, 2, 3])
print("Array a: \n", a)

Array a: 
 [1 2 3]


In [3]:
# Create an array with evenly spaced values

b = np.arange(0, 10, 2) # Values from 0 to 10 [(n-1) rule] with step 2
print("Array b: \n", b)

Array b: 
 [0 2 4 6 8]


In [4]:
# Create an array filled with zeros

d = np.zeros((2,3)) # (2x3) array of zeros
print("Array d: \n", d)

Array d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Create an array filled with zeros

d = np.zeros((2, 3), dtype = int) # (2x3) array of zeros
print("Array d: \n", d)

Array d: 
 [[0 0 0]
 [0 0 0]]


In [6]:
# Create an array filled with ones

e = np.ones((3, 2)) # (3x2) array of ones
print("Array e: \n", e)

Array e: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Create an identity matrix

f = np.eye(4) # (4x4) identity matrix
print("Identity matrix f: \n", f)

Identity matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Create an identity matrix

f = np.identity(4) # (4x4) identity matrix
print("Identity matrix f: \n", f)

Identity matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Create an identity matrix

f = np.identity(4, dtype = int) # (4x4) identity matrix
print("Identity matrix f: \n", f)

Identity matrix f: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Array manipulation functions

In [10]:
# Reshape an array

a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3)) # Reshape to (1x3)
print("Reshaped array: \n", reshaped)

Reshaped array: 
 [[1 2 3]]


In [11]:
# Reshape an array

a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (3, 1)) # Reshape to (3x1)
print("Reshaped array: \n", reshaped)

Reshaped array: 
 [[1]
 [2]
 [3]]


In [12]:
# Flatten an array

f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
flattened = np.ravel(f1) # Flattened to 1D array
print("Flattened array: \n", flattened)

Flattened array: 
 [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Transpose an array

e1 = np.array([[1, 2], [3, 4], [5, 6]])
transposed = np.transpose(e1) # Transpose the array
print("Transposed array: \n", transposed)

Transposed array: 
 [[1 3 5]
 [2 4 6]]


In [14]:
# Stack arrays vertically

a2 = np.array([1, 2, 3])
b2 = np.array([4, 5, 6])
c2 = np.array([7, 8, 9])
stacked = np.vstack([a2, b2, c2]) # Stack a2, b2 and c2 vertically
print("Stacked arrays: \n", stacked)

Stacked arrays: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Stack arrays horizontally

a2 = np.array([1, 2, 3])
b2 = np.array([4, 5, 6])
c2 = np.array([7, 8, 9])
stacked = np.hstack([a2, b2, c2]) # Stack a2, b2 and c2 horizontally
print("Stacked array: \n", stacked)

Stacked array: 
 [1 2 3 4 5 6 7 8 9]


## Mathematical functions

In [16]:
g = np.array([1, 2, 3, 4, 5])
g

array([1, 2, 3, 4, 5])

In [17]:
# Add two arrays

added = np.add(g, 2) # Add 2 to each element 
print("Added 2 to each element of g: \n", added)

Added 2 to each element of g: 
 [3 4 5 6 7]


In [18]:
# Square each element

squared = np.power(g, 2) # Square each element
print("Squared g: \n", squared)

Squared g: 
 [ 1  4  9 16 25]


In [19]:
# Square root of each element

sqrt_val = np.sqrt(g) # Square root of each element
print("Square root of g: \n", sqrt_val)

Square root of g: 
 [1.         1.41421356 1.73205081 2.         2.23606798]


In [20]:
# Dot product of two arrays

a3 = np.array([1, 2, 3])
a4 = np.array([4, 5, 6])
dot_product = np.dot(a3, a4) # Dot product of a3 and a4
print("Dot product of a3 and a4: \n", dot_product)

Dot product of a3 and a4: 
 32


In [21]:
# Cross product of two arrays

a3 = np.array([1, 2, 3])
a4 = np.array([4, 5, 6])
cross_product = np.cross(a3, a4) # Cross product of a3 and a4
print("Cross product of a3 and a4: \n", cross_product)

Cross product of a3 and a4: 
 [-3  6 -3]


## Statistical functions

In [22]:
s = np.array([1, 2, 3, 4, 5])
s

array([1, 2, 3, 4, 5])

In [23]:
# Mean of an array

mean = np.mean(s) 
print("Mean of s: \n", mean)

Mean of s: 
 3.0


In [24]:
# Variance of an array

var = np.var(s)
print("Variance of s: \n", var)

Variance of s: 
 2.0


In [25]:
# Standard deviation of an array

std_dev = np.std(s) 
print("Standard deviation: \n", std_dev)

Standard deviation: 
 1.4142135623730951


In [26]:
# Minimum element of an array

minimum = np.min(s)
print("Minimum of s: \n", minimum)

Minimum of s: 
 1


In [27]:
# Maximum element of an array

maximum = np.max(s)
print("Maximum of s: \n", maximum)

Maximum of s: 
 5


In [28]:
# Sum of array elements

sum_array = np.sum(s)
print("Sum of elements of s: \n", sum_array)

Sum of elements of s: 
 15


## Random sampling functions

In [29]:
# Generate random values between 0 and 1

random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values: \n", random_vals)

Random values: 
 [0.22526444 0.39432771 0.93730257]


In [30]:
# Set seed for reproducibility

np.random.seed(0)
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values: \n", random_vals)

Random values: 
 [0.5488135  0.71518937 0.60276338]


In [31]:
# Generate random integers

rand_ints = np.random.randint(0, 10, size = 5) # 5 random integers between 0 to 10 [(n-1) rule]
print("Random integers: \n", rand_ints)

Random integers: 
 [3 7 9 3 5]


In [32]:
# Set seed for reproducibility

np.random.seed(0)
rand_ints = np.random.randint(0, 10, size = 5) # 5 random integers between 0 to 10 [(n-1) rule]
print("Random integers: \n", rand_ints)

Random integers: 
 [5 0 3 3 7]


## Boolean and Logical functions

In [33]:
# all() 

logical_test = np.array([True, False, True])
all_true = np.all(logical_test) # All True then result is True
print(all_true)

False


In [34]:
logical_test = np.array([True, True, True])
all_true = np.all(logical_test) # All True then result is True
print(all_true)

True


In [35]:
# any() 

logical_test = np.array([True, False, True])
any_true = np.any(logical_test) # All False then result is False
print(any_true)

True


In [36]:
logical_test = np.array([False, False, False])
any_true = np.any(logical_test) # All False then result is False
print(any_true)

False


## Set operations

In [37]:
set_a = np.array([1, 2, 3, 4, 5])
set_a

array([1, 2, 3, 4, 5])

In [38]:
set_b = np.array([3, 4, 5, 6, 7])
set_b

array([3, 4, 5, 6, 7])

In [39]:
# Intersection of two arrays

intersection = np.intersect1d(set_a, set_b)
print("Intersection of set_a and set_b: \n", intersection)

Intersection of set_a and set_b: 
 [3 4 5]


In [40]:
# Union of two arrays

union = np.union1d(set_a, set_b)
print("Union of set_a and set_b: \n", union)

Union of set_a and set_b: 
 [1 2 3 4 5 6 7]


## Array attributes

In [41]:
a = np.array([1, 2, 3, 4, 5])

shape = a.shape # Shape of the array
size = a.size # Number of elements
dimensions = a.ndim # Number of dimensions
dtype = a.dtype # Data type of the array elements

print("Shape of a: \n", shape)
print("Size of a: \n", size)
print("Number of dimensions of a: \n", dimensions)
print("Data type of a: \n", dtype)

Shape of a: 
 (5,)
Size of a: 
 5
Number of dimensions of a: 
 1
Data type of a: 
 int64


## Other functions

In [42]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [43]:
# Create copy of an array

copied_array = np.copy(a) # Create a copy of array a
print("Copied array: \n", copied_array)

Copied array: 
 [1 2 3]


In [44]:
# Size in bytes of an array

array_size_in_bytes = a.nbytes # Size in bytes
print("Size of a in bytes: \n", array_size_in_bytes)

Size of a in bytes: 
 24


In [45]:
# Checks if two arrays share memory

shared = np.shares_memory(a, copied_array) # True if a and copied_array share memory
print("Do a and copied_array share memory: \n", shared)

Do a and copied_array share memory: 
 False
