# NumPy reshape()

In [1]:
import numpy as np

In [2]:
mydata = np.arange(0, 20)
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
np.reshape(mydata, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
mat1 = np.reshape(mydata, (5, 4), order = 'C') # Row major
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
print(mat1[4, 3])

19


In [8]:
print(mat1[3, 3])

15


In [9]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
print(mat1[-3, -1])

11


In [11]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
mat2 = np.reshape(mydata, (5, 4), order = 'F') # Column major
mat2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [14]:
print(mat2[4, 3])

19


In [15]:
print(mat2[0, 2])

10


In [16]:
mat2[0:2]

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16]])

In [17]:
mat2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [18]:
mat2[1:2]

array([[ 1,  6, 11, 16]])

In [19]:
print(mat2[1, 2])

11


In [20]:
mat2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [21]:
print(mat2[-2, -1])

18


In [22]:
print(mat2[-3, -3])

7


In [23]:
mat2[0:2]

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16]])

In [24]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
mat3 = np.reshape(mydata, (5, 4), order = 'A') # Any (automatic) 
mat3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
mat2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [27]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
a1 = ['welcome', 'to', 'datascience']
a2 = ['required', 'hard', 'work']
a3 = ['1', '2', '3']

In [29]:
[a1, a2, a3] # List of list

[['welcome', 'to', 'datascience'],
 ['required', 'hard', 'work'],
 ['1', '2', '3']]

In [30]:
np.array([a1, a2, a3]) # Single 3x3 array

array([['welcome', 'to', 'datascience'],
       ['required', 'hard', 'work'],
       ['1', '2', '3']], dtype='<U11')